export const GETALL_OUR_SERVICES_START = "GETALL_OUR_SERVICES_START";
export const GETALL_OUR_SERVICES_SUCCESS = "GETALL_OUR_SERVICES_SUCCESS";
export const GETALL_OUR_SERVICES_ERROR = "GETALL_OUR_SERVICES_ERROR";

export const GETALL_OUR_PRODUCT_START = "GETALL_OUR_PRODUCT_START";
export const GETALL_OUR_PRODUCT_SUCCESS = "GETALL_OUR_PRODUCT_SUCCESS";
export const GETALL_OUR_PRODUCT_ERROR = "GETALL_OUR_PRODUCT_ERROR";

export const GETALL_OUR_BLOG_START = "GETALL_OUR_BLOG_START";
export const GETALL_OUR_BLOG_SUCCESS = "GETALL_OUR_BLOG_SUCCESS";
export const GETALL_OUR_BLOG_ERROR = "GETALL_OUR_BLOG_ERROR";

export const GETALL_OUR_CLIENT_START = "GETALL_OUR_CLIENT_START";
export const GETALL_OUR_CLIENT_SUCCESS = "GETALL_OUR_CLIENT_SUCCESS";
export const GETALL_OUR_CLIENT_ERROR = "GETALL_OUR_CLIENT_ERROR";

export const GET_ALL_CURRENT_OPENINGS_START = "GET_ALL_CURRENT_OPENINGS_START";
export const GET_ALL_CURRENT_OPENINGS_SUCCESS = "GET_ALL_CURRENT_OPENINGS_SUCCESS";
export const GET_ALL_CURRENT_OPENINGS_ERROR = "GET_ALL_CURRENT_OPENINGS_ERROR";

export const CONTACT_US_START = "CONTACT_US_START";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_ERROR = "CONTACT_US_ERROR";

export const GETALL_EMPLOYEE_START = "GETALL_EMPLOYEE_START";
export const GETALL_EMPLOYEE_SUCCESS = "GETALL_EMPLOYEE_SUCCESS";
export const GETALL_EMPLOYEE_ERROR = "GETALL_EMPLOYEE_ERROR";


