export const GETALL_OUR_SERVICES_START = "GETALL_OUR_SERVICES_START"
export const GETALL_OUR_SERVICES_SUCCESS = "GETALL_OUR_SERVICES_SUCCESS"
export const GETALL_OUR_SERVICES_ERROR = "GETALL_OUR_SERVICES_ERROR"

export const GETALL_OUR_PRODUCT_START = "GETALL_OUR_PRODUCT_START"
export const GETALL_OUR_PRODUCT_SUCCESS = "GETALL_OUR_PRODUCT_SUCCESS"
export const GETALL_OUR_PRODUCT_ERROR = "GETALL_OUR_PRODUCT_ERROR"

export const GETALL_OUR_BLOG_START = "GETALL_OUR_BLOG_START"
export const GETALL_OUR_BLOG_SUCCESS = "GETALL_OUR_BLOG_SUCCESS"
export const GETALL_OUR_BLOG_ERROR = "GETALL_OUR_BLOG_ERROR"

export const GETALL_OUR_CLIENT_START = "GETALL_OUR_CLIENT_START"
export const GETALL_OUR_CLIENT_SUCCESS = "GETALL_OUR_CLIENT_SUCCESS"
export const GETALL_OUR_CLIENT_ERROR = "GETALL_OUR_CLIENT_ERROR"

