import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import HomePage from "./HomePage";
import store from "@/Redux/store";
import { Provider } from "react-redux";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className={styles.main}>
          <HomePage />
      {/* </Provider> */}
        </main>
    </>
  );
}
